name: Auto reply to new issues and PRs

on:
    issues:
        types: [ opened ]
    pull_request:
        branches: [ main, dev ]
        types: [ opened ]

jobs:
    greeting:
        runs-on: ubuntu-latest

        permissions:
            pull-requests: write
            issues: write

        steps:
            -   uses: actions/first-interaction@v3
                with:
                    repo-token: ${{ secrets.GITHUB_TOKEN }}
                    issue-message: |
                        Hi there 👋,

                        Thank you so much for your attention to PyGrinder and PyPOTS! You can follow me on GitHub to receive the latest news of PyGrinder and PyPOTS. If you find PyGrinder helpful to your work, please star⭐️ this repository. Your star is your recognition, which can help more people notice PyPOTS and grow PyPOTS community. It matters and is definitely a kind of contribution to the community.

                        I have received your message and will respond ASAP. Thank you for your patience! 😃

                        Best,
                        Wenjie
                    pr-message: |
                        Hi there 👋,

                        We really really appreciate that you have taken the time to make this PR on PyGrinder!

                        If you are trying to fix a bug, please reference the issue number in the description or give your details about the bug.
                        If you are implementing a feature request, please check with the maintainers that the feature will be accepted first.

                        Best,
                        Wenjie
